version: '3.9'

networks:
  default:
    driver: bridge

services:
  app:
    container_name: sgmc.test
    build:
      context: .
      dockerfile: SGMC.Test/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    networks:
      - default
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SGMC
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
